brew tap caskroom/cask
brew tap djl/homebrew-apache2
brew tap homebrew/versions
brew tap homebrew/binary
brew tap homebrew/dupes
brew tap homebrew/homebrew-php

brew install apache24
brew install autoconf
brew install automake
brew install boost
brew install brew-cask
brew install bsdmake
brew install cloog
brew install cmake
brew install cscope
brew install curl
brew install dirmngr
brew install ffmpeg
brew install freetype
brew install gcc
brew install gdbm
brew install geos
brew install gettext
brew install gflags
brew install ghostscript
brew install git
brew install git-extras
brew install glog
brew install gmp
brew install gnupg
brew install gnupg2
brew install gnutls
brew install go
brew install go-app-engine-64
brew install gpg-agent
brew install htop-osx
brew install icu4c
brew install imagemagick
brew install isl
brew install jansson
brew install jbig2dec
brew install jpeg
brew install lame
brew install libassuan
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgit2
brew install libgpg-error
brew install libksba
brew install libmpc
brew install libpng
brew install libsodium
brew install libtasn1
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libvirt
brew install libvo-aacenc
brew install libyaml
brew install little-cms2
brew install lz4
brew install macvim
brew install makedepend
brew install maven
brew install maven2
brew install memcached
brew install mercurial
brew install mongodb
brew install mpfr
brew install msgpack
brew install mysql
brew install nettle
brew install nginx
brew install nmap
brew install node
brew install openssl
brew install osquery
brew install packer
brew install pcre
brew install phantomjs
brew install php55
brew install pinentry
brew install pkg-config
brew install proctools
brew install pth
brew install pypy
brew install pypy3
brew install python
brew install python3
brew install readline
brew install redis
brew install rocksdb
brew install ruby
brew install snappy
brew install sqlite
brew install subversion
brew install swig
brew install thrift
brew install tmux
brew install tree
brew install unixodbc
brew install vim
brew install x264
brew install xvid
brew install xz
brew install yajl
brew install zeromq
brew install zlib
brew install zsh