brew tap caskroom/cask
brew tap drone/drone
brew tap homebrew/binary
brew tap homebrew/boneyard
brew tap homebrew/cask
brew tap homebrew/cask-versions
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap wagoodman/dive

brew install --cask chromedriver
brew install --cask google-cloud-sdk
brew install --cask java
brew install --cask java8
brew install --cask mattermost
brew install --cask thunderbird
brew install --cask vlc
brew install --cask wkhtmltopdf

brew install abseil
brew install adns
brew install aom
brew install apr
brew install apr-util
brew install autoconf
brew install automake
brew install bazaar
brew install bdw-gc
brew install boost
brew install brotli
brew install bsdmake
brew install c-ares
brew install cairo
brew install cargo-c
brew install cmake
brew install cpp-netlib
brew install ctop
brew install cunit
brew install curl
brew install dav1d
brew install dialog
brew install dive
brew install dnsmasq
brew install docbook
brew install docbook-xsl
brew install docutils
brew install dos2unix
brew install doxygen
brew install drone
brew install eigen
brew install erlang
brew install ffmpeg
brew install fftw
brew install flac
brew install flex
brew install fltk
brew install fontconfig
brew install freetds
brew install freetype
brew install frei0r
brew install fribidi
brew install fzf
brew install gcc
brew install gd
brew install gdbm
brew install geckodriver
brew install geoip
brew install geos
brew install gettext
brew install gflags
brew install ghostscript
brew install giflib
brew install git
brew install git-extras
brew install git-lfs
brew install glib
brew install glog
brew install glpk
brew install gmp
brew install gmp@4
brew install gnu-getopt
brew install gnu-sed
brew install gnupg
brew install gnupg2
brew install gnutls
brew install go
brew install gobject-introspection
brew install goreleaser
brew install gpg-agent
brew install grafana
brew install graphite2
brew install graphviz
brew install grpc
brew install gts
brew install guile
brew install harfbuzz
brew install helm
brew install htop
brew install htop-osx
brew install hugo
brew install hwloc
brew install icu4c
brew install ilmbase
brew install imagemagick
brew install influxdb
brew install intltool
brew install isl
brew install isl@0.12
brew install itstool
brew install jansson
brew install jasper
brew install jemalloc
brew install jpeg
brew install kafka
brew install krb5
brew install kube-ps1
brew install kubectx
brew install kubernetes-cli
brew install kubernetes-helm
brew install lame
brew install leptonica
brew install libarchive
brew install libass
brew install libassuan
brew install libb2
brew install libbluray
brew install libcerf
brew install libde265
brew install libev
brew install libevent
brew install libewf
brew install libffi
brew install libgcrypt
brew install libgit2
brew install libgpg-error
brew install libheif
brew install libidn2
brew install libiscsi
brew install libksba
brew install liblqr
brew install libmagic
brew install libmaxminddb
brew install libmemcached
brew install libmetalink
brew install libmpc
brew install libogg
brew install libomp
brew install libpng
brew install libpq
brew install librdkafka
brew install libressl
brew install libsamplerate
brew install libsass
brew install libsndfile
brew install libsodium
brew install libsoxr
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libvidstab
brew install libvirt
brew install libvorbis
brew install libvpx
brew install libxml2
brew install libxmlsec1
brew install libyaml
brew install little-cms2
brew install lua
brew install luajit
brew install lz4
brew install lzlib
brew install lzo
brew install lzop
brew install mcrypt
brew install memcached
brew install mercurial
brew install meson
brew install mhash
brew install minio-mc
brew install modd
brew install mongodb
brew install mpfr
brew install msgpack
brew install mysql
brew install nasm
brew install ncurses
brew install netpbm
brew install nettle
brew install nghttp2
brew install nginx
brew install ninja
brew install nload
brew install nmap
brew install node
brew install npth
brew install nspr
brew install nss
brew install open-mpi
brew install openblas
brew install opencore-amr
brew install openexr
brew install openfortivpn
brew install openjdk
brew install openjpeg
brew install openldap
brew install openssl@1.1
brew install opus
brew install p11-kit
brew install packer
brew install pango
brew install pcre
brew install pcre2
brew install perl
brew install pgbadger
brew install pgbouncer
brew install phantomjs
brew install pinentry
brew install pixman
brew install pkg-config
brew install portaudio
brew install prometheus
brew install protobuf
brew install protobuf-c
brew install prototool
brew install pth
brew install pv
brew install pyenv
brew install pyenv-virtualenv
brew install python@2
brew install python@3.8
brew install python@3.9
brew install rabbitmq
brew install rav1e
brew install rclone
brew install re2
brew install re2c
brew install readline
brew install redis
brew install rtmpdump
brew install rubberband
brew install ruby
brew install rust
brew install sassc
brew install sdl2
brew install shared-mime-info
brew install snappy
brew install source-highlight
brew install speex
brew install sphinx-doc
brew install sqlite
brew install srt
brew install starship
brew install stern
brew install subversion
brew install szip
brew install tbb
brew install tcl-tk
brew install telnet
brew install terraform
brew install tesseract
brew install the_platinum_searcher
brew install theora
brew install tmux
brew install traefik
brew install tree
brew install unbound
brew install unixodbc
brew install utf8proc
brew install vim
brew install watch
brew install webp
brew install wxmac
brew install x264
brew install x265
brew install xmlto
brew install xvid
brew install xz
brew install yajl
brew install yarn
brew install zeromq
brew install zlib
brew install zookeeper
brew install zsh
brew install zstd
