brew tap caskroom/cask
brew tap drone/drone
brew tap go-swagger/go-swagger

brew install adns
brew install ansible
brew install ant
brew install apr
brew install apr-util
brew install arpack
brew install asio
brew install augeas
brew install autoconf
brew install automake
brew install bazaar
brew install bfg
brew install bison
brew install boost
brew install bsdmake
brew install cairo
brew install chromedriver
brew install cloog
brew install cmake
brew install cscope
brew install curl
brew install dirmngr
brew install dos2unix
brew install doxygen
brew install drone
brew install epstool
brew install erlang
brew install erlang@19
brew install exiftool
brew install ffmpeg
brew install fftw
brew install fltk
brew install fontconfig
brew install freetype
brew install gcc
brew install gd
brew install gdbm
brew install geckodriver
brew install geoip
brew install geos
brew install gettext
brew install gflags
brew install ghostscript
brew install git
brew install git-extras
brew install git-lfs
brew install gl2ps
brew install glib
brew install glide
brew install glog
brew install glpk
brew install gmp
brew install gmp@4
brew install gnu-getopt
brew install gnu-sed
brew install gnupg
brew install gnupg2
brew install gnuplot
brew install gnutls
brew install go
brew install go-swagger
brew install goaccess
brew install gobject-introspection
brew install gpg-agent
brew install grafana
brew install graphicsmagick
brew install graphite2
brew install graphviz
brew install harfbuzz
brew install hdf5
brew install htop-osx
brew install hugo
brew install icu4c
brew install imagemagick
brew install influxdb
brew install intltool
brew install isl
brew install isl@0.12
brew install jansson
brew install jbig2dec
brew install jpeg
brew install lame
brew install latex2rtf
brew install leptonica
brew install libarchive
brew install libassuan
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgit2
brew install libgpg-error
brew install libksba
brew install libmagic
brew install libmemcached
brew install libmpc
brew install libpng
brew install libressl
brew install libsass
brew install libsodium
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libvirt
brew install libvo-aacenc
brew install libxml2
brew install libyaml
brew install little-cms2
brew install lldpd
brew install lua
brew install lz4
brew install lzo
brew install lzop
brew install macvim
brew install makedepend
brew install mcrypt
brew install memcached
brew install mercurial
brew install metis
brew install mhash
brew install minio-mc
brew install mongodb
brew install mpfr
brew install msgpack
brew install mysql
brew install nettle
brew install nginx
brew install nload
brew install nmap
brew install node
brew install npth
brew install octave
brew install openjpeg
brew install openssl
brew install openssl@1.1
brew install osquery
brew install p11-kit
brew install packer
brew install pandoc
brew install pango
brew install pcre
brew install perl
brew install pgbadger
brew install phantomjs
brew install pinentry
brew install pixman
brew install pkg-config
brew install plotutils
brew install poppler
brew install proctools
brew install prometheus
brew install pstoedit
brew install pth
brew install pv
brew install pypy
brew install pypy3
brew install pyqt
brew install pyqt5
brew install python
brew install python3
brew install qhull
brew install qrupdate
brew install qscintilla2
brew install qt
brew install qt5
brew install qt@5.7
brew install rabbitmq
brew install rclone
brew install readline
brew install redis
brew install rocksdb
brew install rtmpdump
brew install ruby
brew install sassc
brew install selenium-server-standalone
brew install sip
brew install sleuthkit
brew install snappy
brew install sqlite
brew install subversion
brew install suite-sparse
brew install swagger-codegen
brew install swig
brew install szip
brew install tbb
brew install tesseract
brew install texinfo
brew install the_platinum_searcher
brew install thrift
brew install tmux
brew install tokyo-cabinet
brew install transfig
brew install tree
brew install ttfautohint
brew install unixodbc
brew install utf8proc
brew install vault
brew install veclibfort
brew install vegeta
brew install vim
brew install watch
brew install webp
brew install wxmac
brew install x264
brew install xvid
brew install xz
brew install yajl
brew install yara
brew install yarn
brew install zeromq
brew install zlib
brew install zsh
