install cloog
install cmake
install cscope
install curl
install freetype
install gcc
install gdbm
install ghostscript
install git
install git-extras
install gmp
install go
install htop-osx
install imagemagick
install isl
install jbig2dec
install jpeg
install libevent
install libmpc
install libpng
install libtiff
install libtool
install libyaml
install little-cms2
install macvim
install makedepend
install memcached
install mercurial
install mongodb
install mpfr
install msgpack
install nginx
install openssl
install pcre
install pkg-config
install pypy
install python
install python3
install readline
install redis
install ruby
install sqlite
install swig
install tree
install xz
install zeromq
