install cloog
install cmake
install cscope
install curl
install docker
install freetype
install gcc
install gdbm
install ghostscript
install git
install git-extras
install gmp
install go
install htop-osx
install imagemagick
install isl
install jbig2dec
install jpeg
install libevent
install libgit2
install libmpc
install libpng
install libtiff
install libtool
install libyaml
install little-cms2
install macvim --override-system-vim
install makedepend
install memcached
install mercurial
install mongodb
install mpfr
install msgpack
install nginx
install node
install openssl
install pcre
install phantomjs
install pkg-config
install pypy
install python --universal
install python3 --universal
install readline
install redis
install ruby
install sqlite
install swig
install tree
install xz
install zeromq
