add_newline = true

[aws]
disabled = true

[battery]
disabled = true

[character]
disabled = false
success_symbol = "[➜](bold green)"

[cmake]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
disabled = false
truncate_to_repo = false
truncation_length = 0

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
disabled = false
symbol = " "

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = false

[golang]
disabled = false
symbol = " "

[helm]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = false

[lua]
disabled = true

[memory_usage]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = false
pyenv_version_name = false
symbol = " "

[ruby]
disabled = true

[rust]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = true

[swift]
disabled = true

[terraform]
disabled = false

[time]
disabled = true

[username]
disabled = false
show_always = true

[zig]
disabled = true
